spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: vladimir
    password: vladimir
    hikari:
      schema: cinema_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS cinema_schema
      connection-timeout: 10000