spring:
  jpa:
    generate-ddl: true
#    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: vladimir
    password: vladimir
    hikari:
      schema: cinema_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS cinema_schema
      connection-timeout: 10000
#  sql:
#    init:
#      mode:
#        always
server:
  port: 8080